### ISSUE TITLE
Missing installer

### ISSUE THREAD

**Issue by markob94** [washonrails/dotfiles#2]
Hi,

The installer is missing . Did you removed it or it is by the accident :)

**Comment by washonrails** [comment]
> Hi,
> 
> The installer is missing . Did you removed it or it is by the accident :)


Thanks a lot , i remove the installer bcuz the script its badly done ,  but i'm already working on it and now that you mentioned this issue I'm going to put a warning in the repository that it's not finished. tysm

**Comment by markob94** [comment]
> > Hi,
> > 
> > The installer is missing . Did you removed it or it is by the accident :)
> 
> 
> Thanks a lot , i remove the installer bcuz the script its badly done ,  but i'm already working on it and now that you mentioned this issue I'm going to put a warning in the repository that it's not finished. tysm

No problem. Too bad that you done with i3 :) but as I can see that you are using hyprland, maybe you can share those dots! But anyways, thanks

**Comment by washonrails** [comment]
> > > Hi,
> > > The installer is missing . Did you removed it or it is by the accident :)
> > 
> > 
> > Thanks a lot , i remove the installer bcuz the script its badly done ,  but i'm already working on it and now that you mentioned this issue I'm going to put a warning in the repository that it's not finished. tysm
> 
> No problem. Too bad that you done with i3 :) but as I can see that you are using hyprland, maybe you can share those dots! But anyways, thanks

I will share my hyprland dots for sure ! Thanks for choosing my dots haha, i didn't know I had so much visibility that someone would want my dotfiles!!

**Comment by markob94** [comment]
> > > > Hi,
> > > > The installer is missing . Did you removed it or it is by the accident :)
> > > 
> > > 
> > > Thanks a lot , i remove the installer bcuz the script its badly done ,  but i'm already working on it and now that you mentioned this issue I'm going to put a warning in the repository that it's not finished. tysm
> > 
> > No problem. Too bad that you done with i3 :) but as I can see that you are using hyprland, maybe you can share those dots! But anyways, thanks
> 
> I will share my hyprland dots for sure ! Thanks for choosing my dots haha, i didn't know I had so much visibility that someone would want my dotfiles!!

Yeah, but I choose them in wrong time :( hehe
